module.exports = {
    apps: [
        {
            name: 'user',
            script: "go",
            args: ["run", "user.go", "-f", "etc/user-godev.yaml"],
            interpreter: 'none',
            autorestart: false,
            watch: false,
            cwd: './apps/user/rpc',
        },
        // {
        //     name: 'user2',
        //     script: "go",
        //     args: ["run", "user.go", "-f", "etc/user-godev_02.yaml"],
        //     interpreter: 'none',
        //     autorestart: false,
        //     watch: false,
        //     cwd: './apps/user/rpc',
        // },
        {
            name: 'pay',
            script: "go",
            args: ["run", "pay.go", "-f", "etc/pay-godev.yaml"],
            interpreter: 'none',
            autorestart: false,
            watch: false,
            cwd: './apps/pay/rpc',
        },
        {
            name: 'product',
            script: "go",
            args: ["run", "product.go", "-f", "etc/product-godev.yaml"],
            interpreter: 'none',
            autorestart: false,
            watch: false,
            cwd: './apps/product/rpc',
        },
        {
            name: 'order',
            script: "go",
            args: ["run", "order.go", "-f", "etc/order-godev.yaml"],
            interpreter: 'none',
            autorestart: false,
            watch: false,
            cwd: './apps/order/rpc',
        },
        {
            name: 'reply',
            script: "go",
            args: ["run", "reply.go", "-f", "etc/reply-godev.yaml"],
            interpreter: 'none',
            autorestart: false,
            watch: false,
            cwd: './apps/reply/rpc',
        },
        // {
        //     name: 'api',
        //     script: "go",
        //     args: ["run", "api.go", "-f", "etc/api-godev.yaml"],
        //     interpreter: 'none',
        //     autorestart: false,
        //     watch: false,
        //     cwd: './apps/app/api',
        // },
    ],
};