// Code generated by goctl. DO NOT EDIT.
// Source: pay.proto

package server

import (
	"context"

	"github.com/zhoushuguang/lebron/apps/pay/rpc/internal/logic"
	"github.com/zhoushuguang/lebron/apps/pay/rpc/internal/svc"
	"github.com/zhoushuguang/lebron/apps/pay/rpc/pay"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Ping(ctx context.Context, in *pay.Request) (*pay.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
